// Auto-generated by scripts/generate_adversarial_tests.py — do not edit.
#include "test_framework.hpp"
#include "json_builder.hpp"
#include "many_keys_100.hpp"
#include "reflection_struct_100.hpp"

#if SIMDJSON_SUPPORTS_CONCEPTS

#include <array>
#include <string>

using namespace simdjson;

namespace {

bool adversarial_ref100_shuffle_3() {
  const char* test_name = "adversarial_ref100_shuffle_3";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_shuffled(3ULL));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k010, 17u);
    STRESS_ASSERT_EQUAL(rec.k050, 57u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_shuffle_7() {
  const char* test_name = "adversarial_ref100_shuffle_7";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_shuffled(7ULL));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k010, 17u);
    STRESS_ASSERT_EQUAL(rec.k050, 57u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_shuffle_11() {
  const char* test_name = "adversarial_ref100_shuffle_11";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_shuffled(11ULL));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k010, 17u);
    STRESS_ASSERT_EQUAL(rec.k050, 57u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_shuffle_19() {
  const char* test_name = "adversarial_ref100_shuffle_19";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_shuffled(19ULL));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k010, 17u);
    STRESS_ASSERT_EQUAL(rec.k050, 57u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_shuffle_42() {
  const char* test_name = "adversarial_ref100_shuffle_42";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_shuffled(42ULL));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k010, 17u);
    STRESS_ASSERT_EQUAL(rec.k050, 57u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_shuffle_99() {
  const char* test_name = "adversarial_ref100_shuffle_99";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_shuffled(99ULL));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k010, 17u);
    STRESS_ASSERT_EQUAL(rec.k050, 57u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_shuffle_48879() {
  const char* test_name = "adversarial_ref100_shuffle_48879";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_shuffled(48879ULL));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k010, 17u);
    STRESS_ASSERT_EQUAL(rec.k050, 57u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_shuffle_3735928559() {
  const char* test_name = "adversarial_ref100_shuffle_3735928559";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_shuffled(3735928559ULL));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k010, 17u);
    STRESS_ASSERT_EQUAL(rec.k050, 57u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_noise_10() {
  const char* test_name = "adversarial_ref100_noise_10";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_with_noise(10));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_noise_50() {
  const char* test_name = "adversarial_ref100_noise_50";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_with_noise(50));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_noise_100() {
  const char* test_name = "adversarial_ref100_noise_100";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_with_noise(100));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_noise_250() {
  const char* test_name = "adversarial_ref100_noise_250";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_with_noise(250));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_noise_500() {
  const char* test_name = "adversarial_ref100_noise_500";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_with_noise(500));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_noise_750() {
  const char* test_name = "adversarial_ref100_noise_750";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_with_noise(750));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_noise_1000() {
  const char* test_name = "adversarial_ref100_noise_1000";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_with_noise(1000));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_duplicates_ignored() {
  const char* test_name = "adversarial_ref100_duplicates_ignored";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_duplicates());
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k050, 57u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_all_members_full_json() {
  const char* test_name = "adversarial_ref100_all_members_full_json";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k001, 8u);
    STRESS_ASSERT_EQUAL(rec.k010, 17u);
    STRESS_ASSERT_EQUAL(rec.k033, 40u);
    STRESS_ASSERT_EQUAL(rec.k050, 57u);
    STRESS_ASSERT_EQUAL(rec.k066, 73u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_ref100_partial_fails_only_k000() {
  const char* test_name = "adversarial_ref100_partial_fails_only_k000";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_only(0, 42));
    ondemand::parser parser;
    reflected_record_100 rec{};
    simdjson::ondemand::document doc{};
    STRESS_ASSERT_ERROR(stress::parse_top(parser, json, doc, rec), NO_SUCH_FIELD);
    return true;
}

bool adversarial_ref100_partial_fails_only_k050() {
  const char* test_name = "adversarial_ref100_partial_fails_only_k050";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_only(50, 999));
    ondemand::parser parser;
    reflected_record_100 rec{};
    simdjson::ondemand::document doc{};
    STRESS_ASSERT_ERROR(stress::parse_top(parser, json, doc, rec), NO_SUCH_FIELD);
    return true;
}

bool adversarial_ref100_partial_fails_except_k042() {
  const char* test_name = "adversarial_ref100_partial_fails_except_k042";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_except(42));
    ondemand::parser parser;
    reflected_record_100 rec{};
    simdjson::ondemand::document doc{};
    STRESS_ASSERT_ERROR(stress::parse_top(parser, json, doc, rec), NO_SUCH_FIELD);
    return true;
}

bool adversarial_ref100_partial_fails_every_5th() {
  const char* test_name = "adversarial_ref100_partial_fails_every_5th";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_every_nth(5));
    ondemand::parser parser;
    reflected_record_100 rec{};
    simdjson::ondemand::document doc{};
    STRESS_ASSERT_ERROR(stress::parse_top(parser, json, doc, rec), NO_SUCH_FIELD);
    return true;
}

bool adversarial_ref100_partial_fails_range_25_75() {
  const char* test_name = "adversarial_ref100_partial_fails_range_25_75";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_range(25, 75));
    ondemand::parser parser;
    reflected_record_100 rec{};
    simdjson::ondemand::document doc{};
    STRESS_ASSERT_ERROR(stress::parse_top(parser, json, doc, rec), NO_SUCH_FIELD);
    return true;
}

bool adversarial_ref100_partial_fails_empty_object() {
  const char* test_name = "adversarial_ref100_partial_fails_empty_object";
  (void)test_name;
  auto json = stress::make_json("{}");
    ondemand::parser parser;
    reflected_record_100 rec{};
    simdjson::ondemand::document doc{};
    STRESS_ASSERT_ERROR(stress::parse_top(parser, json, doc, rec), NO_SUCH_FIELD);
    return true;
}

bool adversarial_ref100_partial_fails_noise_only() {
  const char* test_name = "adversarial_ref100_partial_fails_noise_only";
  (void)test_name;
  auto json = stress::make_json(R"({"zz_noise":1,"other":2})");
    ondemand::parser parser;
    reflected_record_100 rec{};
    simdjson::ondemand::document doc{};
    STRESS_ASSERT_ERROR(stress::parse_top(parser, json, doc, rec), NO_SUCH_FIELD);
    return true;
}

bool adversarial_ref100_full_spot_k000() {
  const char* test_name = "adversarial_ref100_full_spot_k000";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    return true;
}

bool adversarial_ref100_full_spot_k006() {
  const char* test_name = "adversarial_ref100_full_spot_k006";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k006, 13u);
    return true;
}

bool adversarial_ref100_full_spot_k012() {
  const char* test_name = "adversarial_ref100_full_spot_k012";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k012, 19u);
    return true;
}

bool adversarial_ref100_full_spot_k018() {
  const char* test_name = "adversarial_ref100_full_spot_k018";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k018, 25u);
    return true;
}

bool adversarial_ref100_full_spot_k024() {
  const char* test_name = "adversarial_ref100_full_spot_k024";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k024, 31u);
    return true;
}

bool adversarial_ref100_full_spot_k030() {
  const char* test_name = "adversarial_ref100_full_spot_k030";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k030, 37u);
    return true;
}

bool adversarial_ref100_full_spot_k036() {
  const char* test_name = "adversarial_ref100_full_spot_k036";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k036, 43u);
    return true;
}

bool adversarial_ref100_full_spot_k042() {
  const char* test_name = "adversarial_ref100_full_spot_k042";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k042, 49u);
    return true;
}

bool adversarial_ref100_full_spot_k048() {
  const char* test_name = "adversarial_ref100_full_spot_k048";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k048, 55u);
    return true;
}

bool adversarial_ref100_full_spot_k054() {
  const char* test_name = "adversarial_ref100_full_spot_k054";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k054, 61u);
    return true;
}

bool adversarial_ref100_full_spot_k060() {
  const char* test_name = "adversarial_ref100_full_spot_k060";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k060, 67u);
    return true;
}

bool adversarial_ref100_full_spot_k066() {
  const char* test_name = "adversarial_ref100_full_spot_k066";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k066, 73u);
    return true;
}

bool adversarial_ref100_full_spot_k072() {
  const char* test_name = "adversarial_ref100_full_spot_k072";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k072, 79u);
    return true;
}

bool adversarial_ref100_full_spot_k078() {
  const char* test_name = "adversarial_ref100_full_spot_k078";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k078, 85u);
    return true;
}

bool adversarial_ref100_full_spot_k084() {
  const char* test_name = "adversarial_ref100_full_spot_k084";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k084, 91u);
    return true;
}

bool adversarial_ref100_full_spot_k090() {
  const char* test_name = "adversarial_ref100_full_spot_k090";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k090, 97u);
    return true;
}

bool adversarial_ref100_full_spot_k096() {
  const char* test_name = "adversarial_ref100_full_spot_k096";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k096, 103u);
    return true;
}

bool adversarial_ref100_fail_string_k000() {
  const char* test_name = "adversarial_ref100_fail_string_k000";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_wrong_type(0, "\"oops\""));
    ondemand::parser parser;
    reflected_record_100 rec{};
    simdjson::ondemand::document doc{};
    STRESS_ASSERT_ERROR(stress::parse_top(parser, json, doc, rec), INCORRECT_TYPE);
    return true;
}

bool adversarial_ref100_fail_null_k010() {
  const char* test_name = "adversarial_ref100_fail_null_k010";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_wrong_type(10, "null"));
    ondemand::parser parser;
    reflected_record_100 rec{};
    simdjson::ondemand::document doc{};
    STRESS_ASSERT_ERROR(stress::parse_top(parser, json, doc, rec), INCORRECT_TYPE);
    return true;
}

bool adversarial_ref100_fail_bool_k025() {
  const char* test_name = "adversarial_ref100_fail_bool_k025";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_wrong_type(25, "true"));
    ondemand::parser parser;
    reflected_record_100 rec{};
    simdjson::ondemand::document doc{};
    STRESS_ASSERT_ERROR(stress::parse_top(parser, json, doc, rec), INCORRECT_TYPE);
    return true;
}

bool adversarial_ref100_fail_array_k050() {
  const char* test_name = "adversarial_ref100_fail_array_k050";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_wrong_type(50, "[]"));
    ondemand::parser parser;
    reflected_record_100 rec{};
    simdjson::ondemand::document doc{};
    STRESS_ASSERT_ERROR(stress::parse_top(parser, json, doc, rec), INCORRECT_TYPE);
    return true;
}

bool adversarial_ref100_fail_object_k075() {
  const char* test_name = "adversarial_ref100_fail_object_k075";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_wrong_type(75, "{\"x\":1}"));
    ondemand::parser parser;
    reflected_record_100 rec{};
    simdjson::ondemand::document doc{};
    STRESS_ASSERT_ERROR(stress::parse_top(parser, json, doc, rec), INCORRECT_TYPE);
    return true;
}

bool adversarial_ref100_fail_string_k099() {
  const char* test_name = "adversarial_ref100_fail_string_k099";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_wrong_type(99, "\"end\""));
    ondemand::parser parser;
    reflected_record_100 rec{};
    simdjson::ondemand::document doc{};
    STRESS_ASSERT_ERROR(stress::parse_top(parser, json, doc, rec), INCORRECT_TYPE);
    return true;
}

bool adversarial_matcher100_miss_truncate_last() {
  const char* test_name = "adversarial_matcher100_miss_truncate_last";
  (void)test_name;
  using Sel = generated_many_keys_100::selector;
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("f00_00"), Sel::size());
    return true;
}

bool adversarial_matcher100_miss_extend_last() {
  const char* test_name = "adversarial_matcher100_miss_extend_last";
  (void)test_name;
  using Sel = generated_many_keys_100::selector;
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("f00_0000"), Sel::size());
    return true;
}

bool adversarial_matcher100_miss_suffix() {
  const char* test_name = "adversarial_matcher100_miss_suffix";
  (void)test_name;
  using Sel = generated_many_keys_100::selector;
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("f01_001x"), Sel::size());
    return true;
}

bool adversarial_matcher100_miss_prefix() {
  const char* test_name = "adversarial_matcher100_miss_prefix";
  (void)test_name;
  using Sel = generated_many_keys_100::selector;
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("xf00_000"), Sel::size());
    return true;
}

bool adversarial_matcher100_miss_off_by_one() {
  const char* test_name = "adversarial_matcher100_miss_off_by_one";
  (void)test_name;
  using Sel = generated_many_keys_100::selector;
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("f00_001"), Sel::size());
    return true;
}

bool adversarial_matcher100_miss_near_last() {
  const char* test_name = "adversarial_matcher100_miss_near_last";
  (void)test_name;
  using Sel = generated_many_keys_100::selector;
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("f00_098"), Sel::size());
    return true;
}

bool adversarial_matcher100_miss_past_end() {
  const char* test_name = "adversarial_matcher100_miss_past_end";
  (void)test_name;
  using Sel = generated_many_keys_100::selector;
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("f00_100"), Sel::size());
    return true;
}

bool adversarial_matcher100_miss_first_byte() {
  const char* test_name = "adversarial_matcher100_miss_first_byte";
  (void)test_name;
  using Sel = generated_many_keys_100::selector;
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("g00_000"), Sel::size());
    return true;
}

bool adversarial_matcher100_hit_0() {
  const char* test_name = "adversarial_matcher100_hit_0";
  (void)test_name;
  using Sel = generated_many_keys_100::selector;
    STRESS_ASSERT_EQUAL(stress::probe_match_len<Sel>("f00_000"), 0u);
    return true;
}

bool adversarial_matcher100_hit_1() {
  const char* test_name = "adversarial_matcher100_hit_1";
  (void)test_name;
  using Sel = generated_many_keys_100::selector;
    STRESS_ASSERT_EQUAL(stress::probe_match_len<Sel>("f01_001"), 1u);
    return true;
}

bool adversarial_matcher100_hit_50() {
  const char* test_name = "adversarial_matcher100_hit_50";
  (void)test_name;
  using Sel = generated_many_keys_100::selector;
    STRESS_ASSERT_EQUAL(stress::probe_match_len<Sel>("f32_050"), 50u);
    return true;
}

bool adversarial_matcher100_hit_99() {
  const char* test_name = "adversarial_matcher100_hit_99";
  (void)test_name;
  using Sel = generated_many_keys_100::selector;
    STRESS_ASSERT_EQUAL(stress::probe_match_len<Sel>("f63_099"), 99u);
    return true;
}

bool adversarial_matcher_prefix_a_aa_aaa() {
  const char* test_name = "adversarial_matcher_prefix_a_aa_aaa";
  (void)test_name;
  using Sel = ondemand::key_selector<"a", "aa", "aaa">;
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("a"), 0u);
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("aa"), 1u);
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("aaa"), 2u);
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("aaaa"), Sel::size());
    return true;
}

bool adversarial_matcher_prefix_ab_abc_abcd() {
  const char* test_name = "adversarial_matcher_prefix_ab_abc_abcd";
  (void)test_name;
  using Sel = ondemand::key_selector<"ab", "abc", "abcd">;
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("ab"), 0u);
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("abc"), 1u);
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("abcd"), 2u);
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("abcde"), Sel::size());
    return true;
}

bool adversarial_matcher_prefix_x_xy_xyz() {
  const char* test_name = "adversarial_matcher_prefix_x_xy_xyz";
  (void)test_name;
  using Sel = ondemand::key_selector<"x", "xy", "xyz">;
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("x"), 0u);
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("xy"), 1u);
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("xyz"), 2u);
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("xyzz"), Sel::size());
    return true;
}

bool adversarial_foreach_empty_object() {
  const char* test_name = "adversarial_foreach_empty_object";
  (void)test_name;
  auto json = stress::make_json(R"({})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    auto r = obj.for_each<ondemand::key_selector<"a","b">>([&](std::size_t, ondemand::value) {});
    STRESS_ASSERT_SUCCESS(r.error); STRESS_ASSERT_EQUAL(r.matched_count, 0u);
    return true;
}

bool adversarial_foreach_no_matching_keys() {
  const char* test_name = "adversarial_foreach_no_matching_keys";
  (void)test_name;
  auto json = stress::make_json(R"({"zzz":1,"yyy":2})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t a{}, b{}; auto r = obj.for_each<"alpha","beta">(a, b);
    STRESS_ASSERT_SUCCESS(r.error); STRESS_ASSERT_EQUAL(r.matched_count, 0u);
    return true;
}

bool adversarial_foreach_duplicate_first_wins() {
  const char* test_name = "adversarial_foreach_duplicate_first_wins";
  (void)test_name;
  auto json = stress::make_json(R"({"id":1,"id":999})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t id{}; auto r = obj.for_each<"id">(id);
    STRESS_ASSERT_SUCCESS(r.error); STRESS_ASSERT_EQUAL(id, 1u);
    return true;
}

bool adversarial_foreach_bool_as_uint_fail() {
  const char* test_name = "adversarial_foreach_bool_as_uint_fail";
  (void)test_name;
  auto json = stress::make_json(R"({"n":true})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t n{}; auto r = obj.for_each<"n">(n);
    STRESS_ASSERT_ERROR(r.error, INCORRECT_TYPE);
    return true;
}

bool adversarial_foreach_string_as_uint_fail() {
  const char* test_name = "adversarial_foreach_string_as_uint_fail";
  (void)test_name;
  auto json = stress::make_json(R"({"n":"5"})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t n{}; auto r = obj.for_each<"n">(n);
    STRESS_ASSERT_ERROR(r.error, INCORRECT_TYPE);
    return true;
}

bool adversarial_foreach_null_field() {
  const char* test_name = "adversarial_foreach_null_field";
  (void)test_name;
  auto json = stress::make_json(R"({"a":null,"b":2})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t a{}, b{}; auto r = obj.for_each<"a","b">(a,b);
    STRESS_ASSERT_ERROR(r.error, INCORRECT_TYPE);
    return true;
}

bool adversarial_foreach_array_field() {
  const char* test_name = "adversarial_foreach_array_field";
  (void)test_name;
  auto json = stress::make_json(R"({"a":[1,2],"b":3})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t a{}, b{}; auto r = obj.for_each<"a","b">(a,b);
    STRESS_ASSERT_ERROR(r.error, INCORRECT_TYPE);
    return true;
}

bool adversarial_foreach_nested_object_field() {
  const char* test_name = "adversarial_foreach_nested_object_field";
  (void)test_name;
  auto json = stress::make_json(R"({"a":{"z":1},"b":4})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t a{}, b{}; auto r = obj.for_each<"a","b">(a,b);
    STRESS_ASSERT_ERROR(r.error, INCORRECT_TYPE);
    return true;
}

bool adversarial_foreach_max_uint64() {
  const char* test_name = "adversarial_foreach_max_uint64";
  (void)test_name;
  auto json = stress::make_json(R"({"u":18446744073709551615})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t u{}; auto r = obj.for_each<"u">(u);
    STRESS_ASSERT_SUCCESS(r.error); STRESS_ASSERT_EQUAL(u, 18446744073709551615ULL);
    return true;
}

bool adversarial_foreach_negative_as_uint_fail() {
  const char* test_name = "adversarial_foreach_negative_as_uint_fail";
  (void)test_name;
  auto json = stress::make_json(R"({"u":-1})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t u{}; auto r = obj.for_each<"u">(u);
    STRESS_ASSERT_ERROR(r.error, INCORRECT_TYPE);
    return true;
}

bool adversarial_foreach_float_as_uint_fail() {
  const char* test_name = "adversarial_foreach_float_as_uint_fail";
  (void)test_name;
  auto json = stress::make_json(R"({"u":42.9})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t u{}; auto r = obj.for_each<"u">(u);
    STRESS_ASSERT_ERROR(r.error, INCORRECT_TYPE);
    return true;
}

bool adversarial_foreach_early_stop_noise() {
  const char* test_name = "adversarial_foreach_early_stop_noise";
  (void)test_name;
  auto json = stress::make_json(R"({"a":1,"n0":0,"n1":0,"b":2})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t a{}, b{}; auto r = obj.for_each<"a","b">(a,b);
    STRESS_ASSERT_SUCCESS(r.error); STRESS_ASSERT_EQUAL(a,1u); STRESS_ASSERT_EQUAL(b,2u);
    return true;
}

bool adversarial_foreach_lambda_error_mid() {
  const char* test_name = "adversarial_foreach_lambda_error_mid";
  (void)test_name;
  auto json = stress::make_json(R"({"a":1,"b":2,"c":3})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    auto r = obj.for_each<ondemand::key_selector<"a","b","c">>( [&](ondemand::value)->error_code{return SUCCESS;}, [&](ondemand::value)->error_code{return INCORRECT_TYPE;}, [&](ondemand::value){});
    STRESS_ASSERT_ERROR(r.error, INCORRECT_TYPE);
    return true;
}

bool adversarial_foreach_index_reverse_json() {
  const char* test_name = "adversarial_foreach_index_reverse_json";
  (void)test_name;
  auto json = stress::make_json(R"({"c":3,"b":2,"a":1})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    std::array<uint64_t,3> got{}; auto r = obj.for_each<ondemand::key_selector<"a","b","c">>([&](std::size_t i, ondemand::value v)->error_code{ return v.get(got[i]); });
    STRESS_ASSERT_SUCCESS(r.error); STRESS_ASSERT_EQUAL(got[0],1u); STRESS_ASSERT_EQUAL(got[2],3u);
    return true;
}

bool adversarial_foreach_unicode_value() {
  const char* test_name = "adversarial_foreach_unicode_value";
  (void)test_name;
  auto json = stress::make_json(R"({"name":"Montreal"})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    std::string_view name; auto r = obj.for_each<"name">(name);
    STRESS_ASSERT_SUCCESS(r.error); STRESS_ASSERT_SV_EQUAL(name, "Montreal");
    return true;
}

bool adversarial_foreach_escaped_slash_key() {
  const char* test_name = "adversarial_foreach_escaped_slash_key";
  (void)test_name;
  auto json = stress::make_json(R"({"a/b":1})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t v{}; auto r = obj.for_each<"a/b">(v);
    STRESS_ASSERT_SUCCESS(r.error); STRESS_ASSERT_EQUAL(v, 1u);
    return true;
}

bool adversarial_foreach_nested_lambda() {
  const char* test_name = "adversarial_foreach_nested_lambda";
  (void)test_name;
  auto json = stress::make_json(R"({"root":{"leaf":9}})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t leaf{}; auto r = obj.for_each<"root">([&](ondemand::value v)->error_code{ ondemand::object o; SIMDJSON_TRY(v.get_object().get(o)); return o.for_each<"leaf">(leaf).error; });
    STRESS_ASSERT_SUCCESS(r.error); STRESS_ASSERT_EQUAL(leaf, 9u);
    return true;
}

bool adversarial_foreach_triple_nested() {
  const char* test_name = "adversarial_foreach_triple_nested";
  (void)test_name;
  auto json = stress::make_json(R"({"l1":{"l2":{"l3":7}}})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t v{}; auto r = obj.for_each<"l1">([&](ondemand::value v1)->error_code{ ondemand::object o2; SIMDJSON_TRY(v1.get_object().get(o2)); return o2.for_each<"l2">([&](ondemand::value v2)->error_code{ ondemand::object o3; SIMDJSON_TRY(v2.get_object().get(o3)); return o3.for_each<"l3">(v).error; }).error; });
    STRESS_ASSERT_SUCCESS(r.error); STRESS_ASSERT_EQUAL(v, 7u);
    return true;
}

bool adversarial_foreach_one_of_three() {
  const char* test_name = "adversarial_foreach_one_of_three";
  (void)test_name;
  auto json = stress::make_json(R"({"y":2})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t x{}, y{}, z{}; auto r = obj.for_each<"x","y","z">(x,y,z);
    STRESS_ASSERT_SUCCESS(r.error); STRESS_ASSERT_EQUAL(r.matched_count, 1u); STRESS_ASSERT_EQUAL(y,2u);
    return true;
}

bool adversarial_foreach_all_three() {
  const char* test_name = "adversarial_foreach_all_three";
  (void)test_name;
  auto json = stress::make_json(R"({"z":3,"x":1,"y":2})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t x{}, y{}, z{}; auto r = obj.for_each<"x","y","z">(x,y,z);
    STRESS_ASSERT_SUCCESS(r.error); STRESS_ASSERT_EQUAL(r.matched_count, 3u);
    return true;
}

bool adversarial_manykeys100_reversed() {
  const char* test_name = "adversarial_manykeys100_reversed";
  (void)test_name;
  auto json = stress::make_json(generated_many_keys_100::build_json_ordered(true));
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    using Sel = generated_many_keys_100::selector;
    std::size_t hits = 0;
    auto r = obj.for_each<Sel>([&](std::size_t, ondemand::value) { ++hits; });
    STRESS_ASSERT_SUCCESS(r.error);
    STRESS_ASSERT_EQUAL(r.matched_count, 100u);
    return true;
}

bool adversarial_manykeys100_shuffled_77() {
  const char* test_name = "adversarial_manykeys100_shuffled_77";
  (void)test_name;
  auto json = stress::make_json(generated_many_keys_100::build_json_shuffled(77));
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    using Sel = generated_many_keys_100::selector;
    std::size_t hits = 0;
    auto r = obj.for_each<Sel>([&](std::size_t, ondemand::value) { ++hits; });
    STRESS_ASSERT_SUCCESS(r.error);
    STRESS_ASSERT_EQUAL(r.matched_count, 100u);
    return true;
}

bool adversarial_manykeys100_noise_300() {
  const char* test_name = "adversarial_manykeys100_noise_300";
  (void)test_name;
  auto json = stress::make_json(generated_many_keys_100::build_json_with_noise(300));
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    using Sel = generated_many_keys_100::selector;
    std::size_t hits = 0;
    auto r = obj.for_each<Sel>([&](std::size_t, ondemand::value) { ++hits; });
    STRESS_ASSERT_SUCCESS(r.error);
    STRESS_ASSERT_EQUAL(r.matched_count, 100u);
    return true;
}

bool adversarial_manykeys100_partial_33() {
  const char* test_name = "adversarial_manykeys100_partial_33";
  (void)test_name;
  auto json = stress::make_json(generated_many_keys_100::build_json_partial(33));
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    using Sel = generated_many_keys_100::selector;
    std::size_t hits = 0;
    auto r = obj.for_each<Sel>([&](std::size_t, ondemand::value) { ++hits; });
    STRESS_ASSERT_SUCCESS(r.error);
    STRESS_ASSERT_EQUAL(r.matched_count, 33u);
    return true;
}

bool adversarial_manykeys100_duplicates() {
  const char* test_name = "adversarial_manykeys100_duplicates";
  (void)test_name;
  auto json = stress::make_json(generated_many_keys_100::build_json_with_duplicates());
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    using Sel = generated_many_keys_100::selector;
    std::size_t hits = 0;
    auto r = obj.for_each<Sel>([&](std::size_t, ondemand::value) { ++hits; });
    STRESS_ASSERT_SUCCESS(r.error);
    STRESS_ASSERT_EQUAL(r.matched_count, 100u);
    return true;
}

bool adversarial_manual_for_each_100_fields() {
  const char* test_name = "adversarial_manual_for_each_100_fields";
  (void)test_name;
  auto json = stress::make_json(generated_many_keys_100::build_json_ordered(false));
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    using Sel = generated_many_keys_100::selector;
    std::array<uint64_t, 100> got{};
    auto r = obj.for_each<Sel>([&](std::size_t i, ondemand::value v) -> error_code {
      return v.get(got[i]);
    });
    STRESS_ASSERT_SUCCESS(r.error);
    STRESS_ASSERT_EQUAL(r.matched_count, 100u);
    for (std::size_t i = 0; i < 100; ++i) {
      STRESS_ASSERT_EQUAL(got[i], i);
    }
    return true;
}

bool adversarial_ref100_full_backward() {
  const char* test_name = "adversarial_ref100_full_backward";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(true));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k000, 7u);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}

bool adversarial_matcher_jo_joe_john() {
  const char* test_name = "adversarial_matcher_jo_joe_john";
  (void)test_name;
  using Sel = ondemand::key_selector<"jo", "joe", "john">;
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("jo"), 0u);
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("joe"), 1u);
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("john"), 2u);
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("joh"), Sel::size());
    return true;
}

bool adversarial_matcher_id_screen() {
  const char* test_name = "adversarial_matcher_id_screen";
  (void)test_name;
  using Sel = ondemand::key_selector<"id", "screen_name">;
    static_assert(Sel::window.ok);
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("id"), 0u);
    STRESS_ASSERT_EQUAL(stress::probe_match<Sel>("screen_name"), 1u);
    return true;
}

bool adversarial_foreach_window_id_sn() {
  const char* test_name = "adversarial_foreach_window_id_sn";
  (void)test_name;
  auto json = stress::make_json(R"({"padding":0,"screen_name":"x","id":9})");
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t id{}; std::string_view sn;
    auto r = obj.for_each<ondemand::key_selector<"id","screen_name">>(id, sn);
    STRESS_ASSERT_SUCCESS(r.error);
    STRESS_ASSERT_EQUAL(id, 9u);
    STRESS_ASSERT_SV_EQUAL(sn, "x");
    return true;
}

bool adversarial_ref100_partial_via_for_each() {
  const char* test_name = "adversarial_ref100_partial_via_for_each";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100_only(50, 999));
    ondemand::parser parser;
    ondemand::object obj;
    STRESS_PARSE_OBJECT(parser, json, obj);
    uint64_t k050{};
    auto r = obj.for_each<"k050">(k050);
    STRESS_ASSERT_SUCCESS(r.error);
    STRESS_ASSERT_EQUAL(k050, 999u);
    return true;
}

bool adversarial_ref100_full_member_93() {
  const char* test_name = "adversarial_ref100_full_member_93";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k093, 100u);
    return true;
}

bool adversarial_ref100_full_member_94() {
  const char* test_name = "adversarial_ref100_full_member_94";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k094, 101u);
    return true;
}

bool adversarial_ref100_full_member_95() {
  const char* test_name = "adversarial_ref100_full_member_95";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k095, 102u);
    return true;
}

bool adversarial_ref100_full_member_96() {
  const char* test_name = "adversarial_ref100_full_member_96";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k096, 103u);
    return true;
}

bool adversarial_ref100_full_member_97() {
  const char* test_name = "adversarial_ref100_full_member_97";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k097, 104u);
    return true;
}

bool adversarial_ref100_full_member_98() {
  const char* test_name = "adversarial_ref100_full_member_98";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k098, 105u);
    return true;
}

bool adversarial_ref100_full_member_99() {
  const char* test_name = "adversarial_ref100_full_member_99";
  (void)test_name;
  auto json = stress::make_json(build_reflection_json_100(false));
    ondemand::parser parser;
    reflected_record_100 rec{};
    STRESS_PARSE_TOP(parser, json, rec);
    STRESS_ASSERT_EQUAL(rec.k099, 106u);
    return true;
}


} // namespace

void register_adversarial_tests() {
  STRESS_RUN(adversarial_ref100_shuffle_3);
  STRESS_RUN(adversarial_ref100_shuffle_7);
  STRESS_RUN(adversarial_ref100_shuffle_11);
  STRESS_RUN(adversarial_ref100_shuffle_19);
  STRESS_RUN(adversarial_ref100_shuffle_42);
  STRESS_RUN(adversarial_ref100_shuffle_99);
  STRESS_RUN(adversarial_ref100_shuffle_48879);
  STRESS_RUN(adversarial_ref100_shuffle_3735928559);
  STRESS_RUN(adversarial_ref100_noise_10);
  STRESS_RUN(adversarial_ref100_noise_50);
  STRESS_RUN(adversarial_ref100_noise_100);
  STRESS_RUN(adversarial_ref100_noise_250);
  STRESS_RUN(adversarial_ref100_noise_500);
  STRESS_RUN(adversarial_ref100_noise_750);
  STRESS_RUN(adversarial_ref100_noise_1000);
  STRESS_RUN(adversarial_ref100_duplicates_ignored);
  STRESS_RUN(adversarial_ref100_all_members_full_json);
  STRESS_RUN(adversarial_ref100_partial_fails_only_k000);
  STRESS_RUN(adversarial_ref100_partial_fails_only_k050);
  STRESS_RUN(adversarial_ref100_partial_fails_except_k042);
  STRESS_RUN(adversarial_ref100_partial_fails_every_5th);
  STRESS_RUN(adversarial_ref100_partial_fails_range_25_75);
  STRESS_RUN(adversarial_ref100_partial_fails_empty_object);
  STRESS_RUN(adversarial_ref100_partial_fails_noise_only);
  STRESS_RUN(adversarial_ref100_full_spot_k000);
  STRESS_RUN(adversarial_ref100_full_spot_k006);
  STRESS_RUN(adversarial_ref100_full_spot_k012);
  STRESS_RUN(adversarial_ref100_full_spot_k018);
  STRESS_RUN(adversarial_ref100_full_spot_k024);
  STRESS_RUN(adversarial_ref100_full_spot_k030);
  STRESS_RUN(adversarial_ref100_full_spot_k036);
  STRESS_RUN(adversarial_ref100_full_spot_k042);
  STRESS_RUN(adversarial_ref100_full_spot_k048);
  STRESS_RUN(adversarial_ref100_full_spot_k054);
  STRESS_RUN(adversarial_ref100_full_spot_k060);
  STRESS_RUN(adversarial_ref100_full_spot_k066);
  STRESS_RUN(adversarial_ref100_full_spot_k072);
  STRESS_RUN(adversarial_ref100_full_spot_k078);
  STRESS_RUN(adversarial_ref100_full_spot_k084);
  STRESS_RUN(adversarial_ref100_full_spot_k090);
  STRESS_RUN(adversarial_ref100_full_spot_k096);
  STRESS_RUN(adversarial_ref100_fail_string_k000);
  STRESS_RUN(adversarial_ref100_fail_null_k010);
  STRESS_RUN(adversarial_ref100_fail_bool_k025);
  STRESS_RUN(adversarial_ref100_fail_array_k050);
  STRESS_RUN(adversarial_ref100_fail_object_k075);
  STRESS_RUN(adversarial_ref100_fail_string_k099);
  STRESS_RUN(adversarial_matcher100_miss_truncate_last);
  STRESS_RUN(adversarial_matcher100_miss_extend_last);
  STRESS_RUN(adversarial_matcher100_miss_suffix);
  STRESS_RUN(adversarial_matcher100_miss_prefix);
  STRESS_RUN(adversarial_matcher100_miss_off_by_one);
  STRESS_RUN(adversarial_matcher100_miss_near_last);
  STRESS_RUN(adversarial_matcher100_miss_past_end);
  STRESS_RUN(adversarial_matcher100_miss_first_byte);
  STRESS_RUN(adversarial_matcher100_hit_0);
  STRESS_RUN(adversarial_matcher100_hit_1);
  STRESS_RUN(adversarial_matcher100_hit_50);
  STRESS_RUN(adversarial_matcher100_hit_99);
  STRESS_RUN(adversarial_matcher_prefix_a_aa_aaa);
  STRESS_RUN(adversarial_matcher_prefix_ab_abc_abcd);
  STRESS_RUN(adversarial_matcher_prefix_x_xy_xyz);
  STRESS_RUN(adversarial_foreach_empty_object);
  STRESS_RUN(adversarial_foreach_no_matching_keys);
  STRESS_RUN(adversarial_foreach_duplicate_first_wins);
  STRESS_RUN(adversarial_foreach_bool_as_uint_fail);
  STRESS_RUN(adversarial_foreach_string_as_uint_fail);
  STRESS_RUN(adversarial_foreach_null_field);
  STRESS_RUN(adversarial_foreach_array_field);
  STRESS_RUN(adversarial_foreach_nested_object_field);
  STRESS_RUN(adversarial_foreach_max_uint64);
  STRESS_RUN(adversarial_foreach_negative_as_uint_fail);
  STRESS_RUN(adversarial_foreach_float_as_uint_fail);
  STRESS_RUN(adversarial_foreach_early_stop_noise);
  STRESS_RUN(adversarial_foreach_lambda_error_mid);
  STRESS_RUN(adversarial_foreach_index_reverse_json);
  STRESS_RUN(adversarial_foreach_unicode_value);
  STRESS_RUN(adversarial_foreach_escaped_slash_key);
  STRESS_RUN(adversarial_foreach_nested_lambda);
  STRESS_RUN(adversarial_foreach_triple_nested);
  STRESS_RUN(adversarial_foreach_one_of_three);
  STRESS_RUN(adversarial_foreach_all_three);
  STRESS_RUN(adversarial_manykeys100_reversed);
  STRESS_RUN(adversarial_manykeys100_shuffled_77);
  STRESS_RUN(adversarial_manykeys100_noise_300);
  STRESS_RUN(adversarial_manykeys100_partial_33);
  STRESS_RUN(adversarial_manykeys100_duplicates);
  STRESS_RUN(adversarial_manual_for_each_100_fields);
  STRESS_RUN(adversarial_ref100_full_backward);
  STRESS_RUN(adversarial_matcher_jo_joe_john);
  STRESS_RUN(adversarial_matcher_id_screen);
  STRESS_RUN(adversarial_foreach_window_id_sn);
  STRESS_RUN(adversarial_ref100_partial_via_for_each);
  STRESS_RUN(adversarial_ref100_full_member_93);
  STRESS_RUN(adversarial_ref100_full_member_94);
  STRESS_RUN(adversarial_ref100_full_member_95);
  STRESS_RUN(adversarial_ref100_full_member_96);
  STRESS_RUN(adversarial_ref100_full_member_97);
  STRESS_RUN(adversarial_ref100_full_member_98);
  STRESS_RUN(adversarial_ref100_full_member_99);
}

#endif // SIMDJSON_SUPPORTS_CONCEPTS
